function [pns] =ship_sim_pdf()

pns.PN_name = 'Ship Simulation for ports';

pns.set_of_Ps = {'p_Arr_Port', 'p_DockArr','p_sadmin','p_Docked', 'p_dadmin','p_ready_to_leave',...
    'p_DockDep','p_finishLoad','p_finishUnload','p_Departed'};
pns.set_of_Ts = {'t_arr','t_wait','t_DArr1','t_DArr2','t_DArr3','t_unload1', 't_unload2', 't_unload3',...
    't_load1','t_load2','t_load3','t_request_to_leave','t_depart','t_Ddep1','t_Ddep2','t_Ddep3'};


pns.set_of_As = {'t_arr','p_Arr_Port',1, 'p_Arr_Port','t_wait',1, ...
't_wait','p_DockArr',1,'p_DockArr','t_DArr1',1, 'p_DockArr','t_DArr2',1,...
'p_DockArr','t_DArr3',1, ...
't_DArr1','p_Docked',1,'t_DArr2','p_Docked',1, ...
't_DArr3','p_Docked',1, ...
'p_Docked','t_unload1',1,'p_Docked','t_unload2',1,'p_Docked','t_unload3',1, ...
't_unload1','p_finishUnload',1,'t_unload2','p_finishUnload',1,'t_unload3','p_finishUnload',1, ...
'p_finishUnload','t_load1',1,'p_finishUnload','t_load2',1,'p_finishUnload','t_load3',1, ...
't_load1','p_finishLoad',1, 't_load2','p_finishLoad',1,'t_load3','p_finishLoad',1, ...
'p_finishLoad','t_request_to_leave',1, 't_request_to_leave','p_ready_to_leave',1, ...
'p_ready_to_leave','t_depart',1,'t_depart','p_DockDep',1, 'p_DockDep','t_Ddep1',1, ...
'p_DockDep','t_Ddep2',1, 'p_DockDep','t_Ddep3',1, 't_Ddep1','p_Departed',1,'t_Ddep2','p_Departed',1, ...
't_Ddep3','p_Departed',1
};