function [pns] =ship_sim_pdf()

pns.PN_name = 'Ship Simulation for ports';

pns.set_of_Ps = {'pArr_Port', 'DockArr','s_admin','Docked', 'd_admin','ready_to_leave','DockDep','finishLoad','finishUnload','Departed'};
pns.set_of_Ts = {'tarr','twait','DArr1','DArr2','DArr3','t_load','t_unload','t_request_to_leave','t_depart','Ddep1','Ddep2','Ddep3'};


pns.set_of_As = {'tarr','pArr_Port',1, 'pArr_Port','twait',1, ...
'twait','DockArr',1,'DockArr','DArr1',1, 'DockArr','DArr2',1,...
'DockArr','DArr3',1, ...
'DArr1','Docked',1,'DArr2','Docked',1, ...
'DArr3','Docked',1, 'Docked','t_load',1, ...
'Docked','t_unload',1,'t_unload','finishUnload',1, ...
'finishUnload','t_load',1, 't_load','finishLoad',1, ...
'finishLoad','t_request_to_leave',1, 't_request_to_leave','ready_to_leave',1, ...
'ready_to_leave','t_depart',1,'t_depart','DockDep',1, 'DockDep','Ddep1',1, ...
'DockDep','Ddep2',1, 'DockDep','Ddep3',1, 'Ddep1','Departed',1,'Ddep2','Departed',1, ...
'Ddep3','Departed',1
};